### PR TITLE
Added color arguments

### LINKED ISSUE #1: Add Option to Enter Color of Cloak
Currently, the color of the cloak can only be Red (Hardcoded) i.e. only using Red color you can be invisible.

Give an option so that users can pass the desired color of cloak (Out of some options) using Command Line Parameter.

**Example** - 
```
python stream.py --color=blue
python stream.py -c blue
```

Also, display how to use this command if the user passes the **-h** (or **--help**) option while running the script.

### PR DESCRIPTION
**Pull request by AnuragGupta806**
fixes #1  
Added color arguments with proper descriptions for command line and modified the code to hide 3 different color of cloak

### CODE REVIEW

**Comment by pirateksh** [comment]
Fix these errors @AnuragGupta806 

Screenshot from 2021-10-07 23-25-01

Other points - 
If a user enters any color other than the specified options, it should not break the code, instead, user should get a message "Invalid Color Entered"

**Comment by AnuragGupta806** [comment]
I have fixed the error
Screenshot 2021-10-07 233738

This is the reply it generates if color is invalid. Should I change it to "Invalid Color entered"?

**Comment by pirateksh** [comment]
The error message is fine, no need to change that.

Just push the updated code to the color_arguments branch of your forked repo.

**Comment by AnuragGupta806** [comment]
I have pushed the updated code

**Pull request merged**
